### ISSUE TITLE
Status bar ilegible while executing

### ISSUE THREAD

**Issue by webJose** [lakshits11/neon-city#1]
Hello!  See this small screenshot:

![Ilegible status bar](https://github.com/lakshits11/neon-city/assets/25540842/b2f09f02-1916-4231-82fb-c907cb6edf63)

As seen here, the status bar changes to this orange-ish color, and the font color is gray/lilac/something?.  This cannot be read.  This is how the status bar shows up while executing (debugging) a project.

**Comment by lakshits11** [comment]
Hy, thanks for the info. The reason for it turning into orangish color is because of the extension which is executing, not my theme's fault. However, I will look into it. Give me complete details for example what extension are you using to execute, whe does it occur etc etc.

**Comment by lakshits11** [comment]
Due to no input, I am closing this issue.

**Comment by webJose** [comment]
Dude, some of us have jobs and cannot work in open source in the middle of the day.  Patience.

I, as far as I know, am not using any extension in particular to debug.  For example, just tell VS Code to debug a URL.  The status bar becomes this color.

**Comment by lakshits11** [comment]
This issue is being caused due to vscode. In my theme, the foreground text color on debug is grey color. Which looks nice on a purple background. On debugging, vscode changes status bar color to orange color, and it does not change the foreground text  color. This is the reason for having text visibility problems.

In setting.json file, add this:
```json
"workbench.colorCustomizations": {
        "[Neon City]": {
            "statusBar.debuggingBackground": "#7e0097",
		"statusBar.debuggingBorder": "#66017a",
		"statusBar.debuggingForeground": "#ffffff",
        },
},
```

Change colors according to your liking.

**Comment by webJose** [comment]
Ok, thanks for the tip.  My question now would be:  Why do I need to do this?  I am using Neon City as my theme.  Isn't this overriding the theme somehow?  I mean:  Shouldn't this change be in the theme itself?

**Comment by lakshits11** [comment]
If you would have read the README, you would have known this theme is made as a side project/hobby. Its not complete in ALL aspects but is suitable and great in many.
Thanks for your issue. Will update its code in next release.

**Comment by lakshits11** [comment]
This theme is made as a side project/hobby. Its not complete in ALL aspects but is suitable and great in many.
Thanks for your issue. Will update its code in next release.

**Comment by webJose** [comment]
Thanks, I'll await the update.

BTW, good decision getting rid of the previous answer.  Cheers.
